vim.keymap.set("i", "<C-c>", "<Esc>", { noremap = true })
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-i>", "<C-i>zz")
vim.keymap.set("n", "n", "nzz")
vim.keymap.set("n", "N", "Nzz")
vim.keymap.set({ "n", "i" }, "<C-h>", "<C-w>h")
vim.keymap.set({ "n", "i" }, "<C-j>", "<C-w>j")
vim.keymap.set({ "n", "i" }, "<C-k>", "<C-w>k")
vim.keymap.set({ "n", "i" }, "<C-l>", "<C-w>l")
vim.keymap.set("n", "<leader>h", ":noh<CR>")
